### ISSUE TITLE
 error 024: "break" or "continue" is out of context

### ISSUE THREAD

**Issue by Owned67** [jbzdarkid/AutoPause#2]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// autopause.sp
// C:\sourcemod-1.6.4.4624\addons\sourcemod\scripting\autopause
.sp(104) : error 024: "break" or "continue" is out of context
//
// 1 Error.
//
// Compilation Time: 0,33 sec
// ----------------------------------------

Press enter to exit ...

**Comment by jbzdarkid** [comment]
I've provided a custom compiler, it's in this repo. I'm also very confused by that error, since line 104 doesn't have a 'break' nor a 'continue'. In fact, neither of those keywords appear anywhere in my code.
